//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Dev
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DevCollectionEntities : DbContext
    {
        public DevCollectionEntities()
            : base("name=DevCollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<FailedLogin> FailedLogins { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuCategory> MenuCategories { get; set; }
        public virtual DbSet<PerformanceData> PerformanceDatas { get; set; }
        public virtual DbSet<somRole> somRoles { get; set; }
        public virtual DbSet<somSite> somSites { get; set; }
        public virtual DbSet<somUserRole> somUserRoles { get; set; }
        public virtual DbSet<somUser> somUsers { get; set; }
        public virtual DbSet<SuccessfulLogin> SuccessfulLogins { get; set; }
    
        public virtual ObjectResult<GetRolesByUser_Result> GetRolesByUser(string caseid)
        {
            var caseidParameter = caseid != null ?
                new ObjectParameter("caseid", caseid) :
                new ObjectParameter("caseid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRolesByUser_Result>("GetRolesByUser", caseidParameter);
        }
    
        public virtual ObjectResult<string> GetUserRole(string caseid, string role)
        {
            var caseidParameter = caseid != null ?
                new ObjectParameter("caseid", caseid) :
                new ObjectParameter("caseid", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserRole", caseidParameter, roleParameter);
        }
    
        public virtual ObjectResult<string> gtp_GetRoleByCaseid(string caseid)
        {
            var caseidParameter = caseid != null ?
                new ObjectParameter("caseid", caseid) :
                new ObjectParameter("caseid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("gtp_GetRoleByCaseid", caseidParameter);
        }
    
        public virtual int SaveErrorLog(string sitename, string processName, string message, string stacktrace, string @params, string useragent)
        {
            var sitenameParameter = sitename != null ?
                new ObjectParameter("sitename", sitename) :
                new ObjectParameter("sitename", typeof(string));
    
            var processNameParameter = processName != null ?
                new ObjectParameter("processName", processName) :
                new ObjectParameter("processName", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var stacktraceParameter = stacktrace != null ?
                new ObjectParameter("stacktrace", stacktrace) :
                new ObjectParameter("stacktrace", typeof(string));
    
            var paramsParameter = @params != null ?
                new ObjectParameter("params", @params) :
                new ObjectParameter("params", typeof(string));
    
            var useragentParameter = useragent != null ?
                new ObjectParameter("useragent", useragent) :
                new ObjectParameter("useragent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveErrorLog", sitenameParameter, processNameParameter, messageParameter, stacktraceParameter, paramsParameter, useragentParameter);
        }
    
        public virtual int SaveFailedLogin(string email, string sitename)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var sitenameParameter = sitename != null ?
                new ObjectParameter("sitename", sitename) :
                new ObjectParameter("sitename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveFailedLogin", emailParameter, sitenameParameter);
        }
    
        public virtual int SavePerformanceData(string appName, Nullable<bool> cacheHit, string functionName, Nullable<long> functionTime, Nullable<System.DateTime> loggedAt, string parameters, string hostname, string username, string useragent)
        {
            var appNameParameter = appName != null ?
                new ObjectParameter("appName", appName) :
                new ObjectParameter("appName", typeof(string));
    
            var cacheHitParameter = cacheHit.HasValue ?
                new ObjectParameter("cacheHit", cacheHit) :
                new ObjectParameter("cacheHit", typeof(bool));
    
            var functionNameParameter = functionName != null ?
                new ObjectParameter("functionName", functionName) :
                new ObjectParameter("functionName", typeof(string));
    
            var functionTimeParameter = functionTime.HasValue ?
                new ObjectParameter("functionTime", functionTime) :
                new ObjectParameter("functionTime", typeof(long));
    
            var loggedAtParameter = loggedAt.HasValue ?
                new ObjectParameter("loggedAt", loggedAt) :
                new ObjectParameter("loggedAt", typeof(System.DateTime));
    
            var parametersParameter = parameters != null ?
                new ObjectParameter("parameters", parameters) :
                new ObjectParameter("parameters", typeof(string));
    
            var hostnameParameter = hostname != null ?
                new ObjectParameter("hostname", hostname) :
                new ObjectParameter("hostname", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var useragentParameter = useragent != null ?
                new ObjectParameter("useragent", useragent) :
                new ObjectParameter("useragent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SavePerformanceData", appNameParameter, cacheHitParameter, functionNameParameter, functionTimeParameter, loggedAtParameter, parametersParameter, hostnameParameter, usernameParameter, useragentParameter);
        }
    
        public virtual int SaveSuccessfulLogin(string email, string sitename)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var sitenameParameter = sitename != null ?
                new ObjectParameter("sitename", sitename) :
                new ObjectParameter("sitename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveSuccessfulLogin", emailParameter, sitenameParameter);
        }
    }
}
