//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int id { get; set; }
        public string processName { get; set; }
        public string message { get; set; }
        public string stacktrace { get; set; }
        public string parameters { get; set; }
        public Nullable<System.DateTime> timeLogged { get; set; }
        public string useragent { get; set; }
        public string sitename { get; set; }
    }
}
