//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> menucategory_id { get; set; }
        public string name { get; set; }
        public string controller { get; set; }
        public string Viewer { get; set; }
        public string icon { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> sequence { get; set; }
        public Nullable<bool> hidden { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string createuser { get; set; }
    
        public virtual MenuCategory MenuCategory { get; set; }
    }
}
