//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceData
    {
        public int ID { get; set; }
        public string sitename { get; set; }
        public string functionName { get; set; }
        public long functionTime { get; set; }
        public System.DateTime loggedAt { get; set; }
        public bool cacheHit { get; set; }
        public string parameters { get; set; }
        public string hostname { get; set; }
        public string username { get; set; }
        public string useragent { get; set; }
    }
}
