//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class somUserRole
    {
        public int userroleid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> roleid { get; set; }
        public string userlogin { get; set; }
        public Nullable<System.DateTime> userdate { get; set; }
    
        public virtual somRole somRole { get; set; }
        public virtual somUser somUser { get; set; }
    }
}
