//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Dev
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuccessfulLogin
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string sitename { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
