//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Reg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrarEntities1 : DbContext
    {
        public RegistrarEntities1()
            : base("name=RegistrarEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvisoryNote> AdvisoryNotes { get; set; }
        public virtual DbSet<AdvisorySociety> AdvisorySocieties { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<vw_Matri_Grad_Dates> vw_Matri_Grad_Dates { get; set; }
    }
}
