//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Southwind
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SouthwindEntities : DbContext
    {
        public SouthwindEntities()
            : base("name=SouthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdvisoryNote> AdvisoryNotes { get; set; }
        public DbSet<AdvisorySociety> AdvisorySocieties { get; set; }
        public DbSet<Personal> Personals { get; set; }
        public DbSet<Student_Misc> Student_Misc { get; set; }
        public DbSet<vw_Matri_Grad_Dates> vw_Matri_Grad_Dates { get; set; }
        public DbSet<v_AdvisorySociety> v_AdvisorySociety { get; set; }
        public DbSet<v_studentsAll> v_studentsAll { get; set; }
        public DbSet<v_StudentsSOM> v_StudentsSOM { get; set; }
        public DbSet<v_StudentsSOMwithReducedFee> v_StudentsSOMwithReducedFee { get; set; }
    }
}
