//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarFeedsBkup8252021
    {
        public int id { get; set; }
        public string case_id { get; set; }
        public string url { get; set; }
        public string prev_calendar_data { get; set; }
        public Nullable<int> canvas_user_id { get; set; }
    }
}
