//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public long UniqueId { get; set; }
        public Nullable<int> CanvasUserID { get; set; }
        public string CanvasCalendarEventID { get; set; }
        public Nullable<System.DateTime> StartAt { get; set; }
        public Nullable<System.DateTime> EndAt { get; set; }
        public string GoogleCalendarEventID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
    }
}
