//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvasSectionEnrollment
    {
        public int id { get; set; }
        public Nullable<int> canvascourse_id { get; set; }
        public string enrollment_state { get; set; }
        public Nullable<bool> limit_prev { get; set; }
        public string type { get; set; }
        public Nullable<int> canvasuser_id { get; set; }
        public Nullable<int> canvasrole_id { get; set; }
        public string start_at { get; set; }
        public string end_at { get; set; }
        public Nullable<int> canvassection_id { get; set; }
    
        public virtual CanvasCourse CanvasCourse { get; set; }
        public virtual CanvasRole CanvasRole { get; set; }
        public virtual CanvasSection CanvasSection { get; set; }
        public virtual CanvasUser CanvasUser { get; set; }
    }
}
