//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvasUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CanvasUser()
        {
            this.CanvasGroupMembers = new HashSet<CanvasGroupMember>();
            this.CanvasSectionEnrollments = new HashSet<CanvasSectionEnrollment>();
            this.zSOMModuleFaculties = new HashSet<zSOMModuleFaculty>();
            this.zSOMModuleFaculties1 = new HashSet<zSOMModuleFaculty>();
        }
    
        public int id { get; set; }
        public string case_id { get; set; }
        public string name { get; set; }
        public string sortable_name { get; set; }
        public string short_name { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvasGroupMember> CanvasGroupMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvasSectionEnrollment> CanvasSectionEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zSOMModuleFaculty> zSOMModuleFaculties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zSOMModuleFaculty> zSOMModuleFaculties1 { get; set; }
    }
}
