//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvasAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CanvasAssignment()
        {
            this.CanvasAssignmentOverrides = new HashSet<CanvasAssignmentOverride>();
            this.SOMAnatomyPresentations = new HashSet<SOMAnatomyPresentation>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> canvasassignmentgroup_id { get; set; }
        public Nullable<int> canvasgroupcategory_id { get; set; }
        public Nullable<int> canvascourse_id { get; set; }
        public Nullable<bool> grade_group_students_individually { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual CanvasAssignmentGroup CanvasAssignmentGroup { get; set; }
        public virtual CanvasCourse CanvasCourse { get; set; }
        public virtual CanvasGroupCategory CanvasGroupCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvasAssignmentOverride> CanvasAssignmentOverrides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMAnatomyPresentation> SOMAnatomyPresentations { get; set; }
    }
}
