//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvasAssignmentOverride
    {
        public int id { get; set; }
        public int canvasassignment_id { get; set; }
        public Nullable<int> canvasgroup_id { get; set; }
        public Nullable<int> canvassection_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> due_at { get; set; }
        public Nullable<System.DateTime> unlock_at { get; set; }
        public Nullable<System.DateTime> lock_at { get; set; }
        public string canvasstudent_ids { get; set; }
    
        public virtual CanvasAssignment CanvasAssignment { get; set; }
        public virtual CanvasGroup CanvasGroup { get; set; }
        public virtual CanvasSection CanvasSection { get; set; }
    }
}
