//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvasModuleItem
    {
        public int id { get; set; }
        public Nullable<int> canvasmodule_id { get; set; }
        public string type { get; set; }
        public Nullable<int> content_id { get; set; }
        public Nullable<System.DateTime> due_at { get; set; }
    
        public virtual CanvasModule CanvasModule { get; set; }
    }
}
