//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvasGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CanvasGroup()
        {
            this.CanvasAssignmentOverrides = new HashSet<CanvasAssignmentOverride>();
            this.CanvasGroupMembers = new HashSet<CanvasGroupMember>();
            this.SOMAnatomyPresentations = new HashSet<SOMAnatomyPresentation>();
            this.SOMFCMGradingGroups = new HashSet<SOMFCMGradingGroup>();
            this.SOMSectionTeams = new HashSet<SOMSectionTeam>();
        }
    
        public int id { get; set; }
        public Nullable<int> canvasgroupcategory_id { get; set; }
        public string name { get; set; }
        public Nullable<int> member_count { get; set; }
        public int unique_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvasAssignmentOverride> CanvasAssignmentOverrides { get; set; }
        public virtual CanvasGroupCategory CanvasGroupCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvasGroupMember> CanvasGroupMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMAnatomyPresentation> SOMAnatomyPresentations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMFCMGradingGroup> SOMFCMGradingGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSectionTeam> SOMSectionTeams { get; set; }
    }
}
