//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvasGroupMember
    {
        public Nullable<int> id { get; set; }
        public Nullable<int> canvasgroup_id { get; set; }
        public Nullable<int> canvasuser_id { get; set; }
        public int unique_id_key { get; set; }
    
        public virtual CanvasGroup CanvasGroup { get; set; }
        public virtual CanvasUser CanvasUser { get; set; }
    }
}
