//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanvasSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CanvasSection()
        {
            this.CanvasAssignmentOverrides = new HashSet<CanvasAssignmentOverride>();
            this.CanvasSectionEnrollments = new HashSet<CanvasSectionEnrollment>();
            this.SOMSectionTeams = new HashSet<SOMSectionTeam>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> canvascourse_id { get; set; }
        public string start_at { get; set; }
        public string end_at { get; set; }
        public Nullable<int> total_students { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvasAssignmentOverride> CanvasAssignmentOverrides { get; set; }
        public virtual CanvasCourse CanvasCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CanvasSectionEnrollment> CanvasSectionEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSectionTeam> SOMSectionTeams { get; set; }
    }
}
