//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMAnatomyPresentation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOMAnatomyPresentation()
        {
            this.SOMAnatomyPresentationMembers = new HashSet<SOMAnatomyPresentationMember>();
        }
    
        public int id { get; set; }
        public int canvasAssignment_id { get; set; }
        public int canvasGroup_id { get; set; }
        public Nullable<int> presentToGroup { get; set; }
        public Nullable<int> presentToCanvasGroup_id { get; set; }
    
        public virtual CanvasAssignment CanvasAssignment { get; set; }
        public virtual CanvasGroup CanvasGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMAnatomyPresentationMember> SOMAnatomyPresentationMembers { get; set; }
    }
}
