//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMCourseHyperlink
    {
        public int id { get; set; }
        public Nullable<int> canvascourse_id { get; set; }
        public Nullable<int> somsectionblock_id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
    
        public virtual CanvasCourse CanvasCourse { get; set; }
        public virtual SOMSectionBlock SOMSectionBlock { get; set; }
    }
}
