//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMCourseClassYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOMCourseClassYear()
        {
            this.SOMSectionFacultyFiles = new HashSet<SOMSectionFacultyFile>();
        }
    
        public Nullable<int> canvascourse_id { get; set; }
        public Nullable<int> seyear { get; set; }
        public Nullable<int> gyr { get; set; }
        public string courseavailto { get; set; }
        public Nullable<int> somsectionblock_id { get; set; }
        public int id { get; set; }
        public Nullable<int> weekmid { get; set; }
        public Nullable<int> weekend { get; set; }
        public Nullable<int> weektotal { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
    
        public virtual CanvasCourse CanvasCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSectionFacultyFile> SOMSectionFacultyFiles { get; set; }
    }
}
