//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMFCMGradingGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOMFCMGradingGroup()
        {
            this.SOMFCMGradingIndividuals = new HashSet<SOMFCMGradingIndividual>();
        }
    
        public int id { get; set; }
        public int somFCMGrading_id { get; set; }
        public int canvasGroup_id { get; set; }
        public string graderId1 { get; set; }
        public string graderId2 { get; set; }
        public string accessLog { get; set; }
    
        public virtual CanvasGroup CanvasGroup { get; set; }
        public virtual SOMFCMGrading SOMFCMGrading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMFCMGradingIndividual> SOMFCMGradingIndividuals { get; set; }
    }
}
