//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMFCMGradingIndividual
    {
        public int id { get; set; }
        public int SOMFCMGradingGroup_id { get; set; }
        public string case_id { get; set; }
        public string graderId1 { get; set; }
        public string graderId2 { get; set; }
        public string accessLog { get; set; }
    
        public virtual SOMFCMGradingGroup SOMFCMGradingGroup { get; set; }
    }
}
