//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMSectionFacultyFile
    {
        public int id { get; set; }
        public Nullable<int> somcourseclassyear_id { get; set; }
        public Nullable<int> canvasmodule_id { get; set; }
        public Nullable<int> somsectionweek_weekid { get; set; }
        public Nullable<int> somsectionfacultyfiletype_id { get; set; }
        public string link { get; set; }
        public string name { get; set; }
        public string user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
        public Nullable<int> seyear_old { get; set; }
        public Nullable<int> bcode_old { get; set; }
        public Nullable<int> wtcode_old { get; set; }
        public Nullable<int> iqfileid_old { get; set; }
        public Nullable<int> fid_old { get; set; }
    
        public virtual CanvasModule CanvasModule { get; set; }
        public virtual SOMCourseClassYear SOMCourseClassYear { get; set; }
        public virtual SOMSectionFacultyFileType SOMSectionFacultyFileType { get; set; }
    }
}
