//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMSectionFacultyNote
    {
        public int id { get; set; }
        public Nullable<int> somsectionfaculty_id { get; set; }
        public string case_id { get; set; }
        public string note { get; set; }
        public string user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
        public Nullable<int> seyear_old { get; set; }
        public Nullable<int> bcode_old { get; set; }
        public Nullable<int> gid_old { get; set; }
        public Nullable<int> fcode_old { get; set; }
        public Nullable<int> wtcode_old { get; set; }
        public string schtype_old { get; set; }
    
        public virtual SOMSectionFaculty SOMSectionFaculty { get; set; }
    }
}
