//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMSectionMember
    {
        public int id { get; set; }
        public Nullable<int> somsectionteam_id { get; set; }
        public string case_id { get; set; }
        public Nullable<int> canvasrole_id { get; set; }
        public string user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
    
        public virtual CanvasRole CanvasRole { get; set; }
        public virtual SOMSectionTeam SOMSectionTeam { get; set; }
    }
}
