//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMStudentFileResource
    {
        public string case_id { get; set; }
        public Nullable<System.Guid> picturesmstream_id { get; set; }
        public Nullable<System.Guid> picturelgstream_id { get; set; }
        public Nullable<System.Guid> soundstream_id { get; set; }
        public byte[] soundstream { get; set; }
        public byte[] picturesmfilestream { get; set; }
        public byte[] picturelgfilestream { get; set; }
    }
}
