//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMSectionWeekSpecial
    {
        public int id { get; set; }
        public Nullable<int> gyr { get; set; }
        public Nullable<int> weeknumber { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> weekstart { get; set; }
        public Nullable<System.DateTime> weekend { get; set; }
        public string user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
        public Nullable<int> wnumcal_old { get; set; }
        public Nullable<int> wtcode_old { get; set; }
    }
}
