//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMSISCourseBlock
    {
        public int id { get; set; }
        public string sissubject { get; set; }
        public string siscatalog_nbr { get; set; }
        public Nullable<int> somsectionblock_id { get; set; }
        public Nullable<int> ayearsubtract { get; set; }
        public Nullable<int> gyradd { get; set; }
        public string description { get; set; }
        public string canvascourse_code { get; set; }
        public string canvascourse_name { get; set; }
        public Nullable<int> canvasuser_role { get; set; }
        public Nullable<int> somuser_role { get; set; }
    
        public virtual SOMSectionBlock SOMSectionBlock { get; set; }
    }
}
