//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMSectionFaculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOMSectionFaculty()
        {
            this.SOMSectionFacultyFeedbacks = new HashSet<SOMSectionFacultyFeedback>();
            this.SOMSectionFacultyNotes = new HashSet<SOMSectionFacultyNote>();
        }
    
        public int id { get; set; }
        public Nullable<int> somsectionteam_id { get; set; }
        public Nullable<int> canvasmodule_id { get; set; }
        public Nullable<int> somsectionweek_weekid { get; set; }
        public Nullable<int> faculty_id { get; set; }
        public Nullable<int> facultyrole_id { get; set; }
        public string user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
        public Nullable<int> seyear_old { get; set; }
        public Nullable<int> bcode_old { get; set; }
        public Nullable<int> gid_old { get; set; }
        public Nullable<int> wtcode_old { get; set; }
        public string schtype_old { get; set; }
        public Nullable<int> roleid_old { get; set; }
    
        public virtual CanvasModule CanvasModule { get; set; }
        public virtual SOMSectionTeam SOMSectionTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSectionFacultyFeedback> SOMSectionFacultyFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSectionFacultyNote> SOMSectionFacultyNotes { get; set; }
    }
}
