//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMSectionBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOMSectionBlock()
        {
            this.SOMCourseHyperlinks = new HashSet<SOMCourseHyperlink>();
            this.SOMSectionTeams = new HashSet<SOMSectionTeam>();
            this.SOMSISCourseBlocks = new HashSet<SOMSISCourseBlock>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string avail_to { get; set; }
        public Nullable<bool> random { get; set; }
        public Nullable<bool> cwru_only { get; set; }
        public Nullable<bool> is_section { get; set; }
        public Nullable<bool> is_group { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMCourseHyperlink> SOMCourseHyperlinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSectionTeam> SOMSectionTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSISCourseBlock> SOMSISCourseBlocks { get; set; }
    }
}
