//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOMSectionTeam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOMSectionTeam()
        {
            this.SOMSectionFaculties = new HashSet<SOMSectionFaculty>();
            this.SOMSectionMembers = new HashSet<SOMSectionMember>();
        }
    
        public int id { get; set; }
        public int somsectionblock_id { get; set; }
        public int grpid { get; set; }
        public Nullable<int> canvascourse_id { get; set; }
        public Nullable<int> canvassection_id { get; set; }
        public Nullable<int> canvasgroup_id { get; set; }
        public Nullable<bool> section_release { get; set; }
        public Nullable<bool> group_release { get; set; }
        public Nullable<System.DateTime> section_release_date { get; set; }
        public Nullable<System.DateTime> group_release_date { get; set; }
        public string user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
    
        public virtual CanvasCourse CanvasCourse { get; set; }
        public virtual CanvasGroup CanvasGroup { get; set; }
        public virtual CanvasSection CanvasSection { get; set; }
        public virtual SOMSectionBlock SOMSectionBlock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSectionFaculty> SOMSectionFaculties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOMSectionMember> SOMSectionMembers { get; set; }
    }
}
