//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpGroupsMedium
    {
        public int id { get; set; }
        public Nullable<int> canvascourse_id { get; set; }
        public int somsectionblock_id { get; set; }
        public string groupcategoryname { get; set; }
        public string grpcode { get; set; }
        public int grpid { get; set; }
        public Nullable<int> iqgrpid1 { get; set; }
        public Nullable<int> iqgrpid2 { get; set; }
        public Nullable<int> iqgrpid3 { get; set; }
    }
}
