//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpGroupsSwap
    {
        public int id { get; set; }
        public string case_id { get; set; }
        public string sex { get; set; }
        public Nullable<int> teamid { get; set; }
        public Nullable<int> pteamid { get; set; }
        public Nullable<int> nteamid { get; set; }
        public Nullable<int> grpid { get; set; }
        public Nullable<int> pgrpid { get; set; }
        public Nullable<int> ngrpid { get; set; }
        public Nullable<int> memberid { get; set; }
    }
}
