//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpGroup
    {
        public int id { get; set; }
        public string gyr { get; set; }
        public Nullable<int> somsectionblock_id { get; set; }
        public double randnum { get; set; }
        public Nullable<int> canvasuser_id { get; set; }
        public string case_id { get; set; }
        public string sex { get; set; }
        public bool is_minority { get; set; }
        public string ethnicity { get; set; }
        public string advisor_email { get; set; }
        public int advisor_id { get; set; }
    }
}
