//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CourseFeed
    {
        public string Crse_ID { get; set; }
        public decimal class_nbr { get; set; }
        public string Strm { get; set; }
        public string subject { get; set; }
        public string catalog_nbr { get; set; }
        public string ayear { get; set; }
        public string course_title { get; set; }
        public System.DateTime start_dt { get; set; }
        public System.DateTime end_dt { get; set; }
        public string course_type { get; set; }
    }
}
