//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Ethnicity
    {
        public string SetID { get; set; }
        public string Ethnic_Grp_CD { get; set; }
        public Nullable<System.DateTime> EffDt { get; set; }
        public string Status { get; set; }
        public string Descr { get; set; }
        public string Short_Descr { get; set; }
        public Nullable<bool> isminority { get; set; }
    }
}
