//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_FacultySom
    {
        public string ln { get; set; }
        public string fn { get; set; }
        public string mn { get; set; }
        public string emplid { get; set; }
        public string email_address { get; set; }
        public string case_id { get; set; }
    }
}
