//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_StudentCoreBlockEnrollment
    {
        public string emaddr { get; set; }
        public string Sex { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string ayear { get; set; }
        public int block_id { get; set; }
        public string coreblocknum { get; set; }
        public string coreblockname { get; set; }
        public string session_id { get; set; }
    }
}
