//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_StudentGroups
    {
        public string Emplid { get; set; }
        public string seyear { get; set; }
        public int blockid { get; set; }
        public string schtype { get; set; }
        public int groupid { get; set; }
        public string blockname { get; set; }
        public string gender_identity { get; set; }
        public string gender_pronoun { get; set; }
    }
}
