//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class zSOMModuleFaculty
    {
        public int id { get; set; }
        public Nullable<int> canvasmodule_id { get; set; }
        public Nullable<int> canvasuser_id { get; set; }
        public int somfacultyrolte_id { get; set; }
    
        public virtual CanvasModule CanvasModule { get; set; }
        public virtual CanvasUser CanvasUser { get; set; }
        public virtual CanvasUser CanvasUser1 { get; set; }
        public virtual SOMFacultyRole SOMFacultyRole { get; set; }
    }
}
