//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grid_and_CRUD.Data.Canvas
{
    using System;
    using System.Collections.Generic;
    
    public partial class zSOMSectionTeamCourse
    {
        public int id { get; set; }
        public Nullable<int> somsectionteam_id { get; set; }
        public Nullable<int> canvascourse_id { get; set; }
        public Nullable<int> canvassection_id { get; set; }
        public Nullable<int> canvasgroup_id { get; set; }
        public Nullable<bool> section_release { get; set; }
        public Nullable<bool> group_release { get; set; }
        public Nullable<System.DateTime> section_release_date { get; set; }
        public Nullable<System.DateTime> group_release_date { get; set; }
        public string user_login { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
    }
}
